name: wa_odoo_sync
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.7.0

dependencies:
  dio: ^5.8.0+1
  envied: ^1.1.1
  freezed_annotation: ^3.0.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  odoo_rpc: ^0.6.0
  logging: ^1.2.0

dev_dependencies:
  build_runner: ^2.4.15
  envied_generator: ^1.1.1
  freezed: ^3.0.3
  json_serializable: ^6.9.4
  lints: ^5.0.0
  test: ^1.24.0

assets:
  - .env
